routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\PaypalController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('create-transaction/{checkout_id?}', [PayPalController::class, 'createTransaction'])->name('createTransaction');
Route::get('process-transaction', [PayPalController::class, 'processTransaction'])->name('processTransaction');
Route::get('success-transaction', [PayPalController::class, 'successTransaction'])->name('successTransaction');
Route::get('cancel-transaction', [PayPalController::class, 'cancelTransaction'])->name('cancelTransaction');


Route::prefix('/customer')->name('customer.')->namespace('Customer')->group(function(){

    /**
     * Admin Auth Route(s)
     */
    Route::namespace('Auth')->group(function(){

        //Login Routes
        Route::get('/login', [\App\Http\Controllers\Customer\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login',[\App\Http\Controllers\Customer\Auth\LoginController::class, 'login'])->name('dologin');
        Route::post('/logout',[\App\Http\Controllers\Customer\Auth\LoginController::class, 'logout'])->name('logout');

        //Register Routes
         Route::get('/register',[\App\Http\Controllers\Customer\Auth\RegisterController::class, 'showRegistrationForm'])->name('register');
         Route::post('/register',[\App\Http\Controllers\Customer\Auth\RegisterController::class, 'doregister'])->name('doregister');

    });

    Route::get('/dashboard',[\App\Http\Controllers\Customer\HomeController::class,'index'])->name('home');

    //Put all of your admin routes here...

});


Route::name('frontend.')->group(function() {
    Route::post('/product/rating', [\App\Http\Controllers\Frontend\FrontendController::class, 'rating'])->name('product.rating');
    Route::post('/category/filter_product', [\App\Http\Controllers\Frontend\FrontendController::class, 'filterProduct'])->name('category.filter_product');
    Route::get('/', [\App\Http\Controllers\Frontend\FrontendController::class, 'index'])->name('index');
    Route::get('/category/{slug}', [\App\Http\Controllers\Frontend\FrontendController::class, 'category'])->name('category');
    Route::get('/subcategory/{slug}', [\App\Http\Controllers\Frontend\FrontendController::class, 'subcategory'])->name('subcategory');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\FrontendController::class, 'product'])->name('product');
    Route::post('/cart/make_order', [\App\Http\Controllers\Frontend\CartController::class, 'makeOrder'])->name('cart.make_order');
});
Route::post('/cart/add', [\App\Http\Controllers\Frontend\CartController::class, 'add'])->name('frontend.cart.add');
Route::get('/cart', [\App\Http\Controllers\Frontend\CartController::class, 'index'])->name('cart.index');
Route::post('/cart/update', [\App\Http\Controllers\Frontend\CartController::class, 'update'])->name('cart.update');
Route::get('/cart/checkout', [\App\Http\Controllers\Frontend\CartController::class, 'checkout'])->name('cart.checkout');
Route::post('/cart/apply_coupon', [\App\Http\Controllers\Frontend\CartController::class, 'applyCoupon'])->name('cart.apply_coupon');

Auth::routes(['register' => true]);
Route::middleware(['auth','permission'])->group(function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});
Route::post('/category/getsubcategory', [\App\Http\Controllers\Backend\CategoryController::class, 'getSubcategory'])->name('category.getsubcategory');

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::prefix('backend')->name('backend.')->middleware(['auth'])->group(function(){
    Route::get('/role/assign_form/{id}', [\App\Http\Controllers\Backend\RoleController::class, 'assignForm'])->name('role.assign_form');
    Route::post('/role/assign_permission', [\App\Http\Controllers\Backend\RoleController::class, 'assignPermission'])->name('role.assign_permission');
    Route::resource('/category', \App\Http\Controllers\Backend\CategoryController::class );
    Route::resource('/subcategory',\App\Http\Controllers\Backend\SubCategoryController::class);
    Route::resource('/product',\App\Http\Controllers\Backend\ProductController::class);
    Route::resource('/unit',\App\Http\Controllers\Backend\UnitController::class);
    Route::resource('/tag', \App\Http\Controllers\Backend\TagController::class );
    Route::resource('/attribute',\App\Http\Controllers\Backend\AttributeController::class);
    Route::resource('/module',\App\Http\Controllers\Backend\ModuleController::class);
    Route::resource('/permission',\App\Http\Controllers\Backend\PermissionController::class);
    Route::resource('/role',\App\Http\Controllers\Backend\RoleController::class);
    Route::resource('/user',\App\Http\Controllers\Backend\UserController::class);
    Route::resource('/setting',\App\Http\Controllers\Backend\SettingController::class);
    Route::resource('/coupon',\App\Http\Controllers\Backend\CouponController::class);
    Route::resource('/rating',\App\Http\Controllers\Backend\RatingController::class);
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class Customer extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'address',
        'country',
        'email',
        'password',
        'contact',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Customer/HomeController.php
<?php

namespace App\Http\Controllers\Customer;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Only Authenticated users for "admin" guard
     * are allowed.
     *
     * @return void
     */
    public function __construct()
    {
        if (!Auth::user()){
            return view('customer.login');
        }
        $this->middleware('auth:customer');
    }

    /**
     * Show Admin Dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        $category =  Category::where('status',1)->get();

        return view('customer.home',compact('category'));
    }
}

resources/views/customer/home.blade.php
@extends('layouts.frontend')

@section('main-content')
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Customer</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="single-product.html">Customer Dashboard</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
        <div class="container">

            <div class="card">
                <div class="card-body login-card-body">
                    <p class="login-box-msg">Dashboard
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                    <form id="logout-form" action="{{ route('customer.logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                    </p>

                  <p>Welcome Customer</p>


                </div>
                <!-- /.login-card-body -->
            </div>

        </div>
    </section>
    <!--================End Checkout Area =================-->

@endsection

resources/views/customer/login.blade.php
@extends('layouts.frontend')

@section('main-content')
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Customer</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="single-product.html">Customer Login</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
        <div class="container">

            <div class="card">
                <div class="card-body login-card-body">

                    <p class="login-box-msg">{{__('login.info')}}</p>

                    <form method="POST" action="{{ route('customer.dologin') }}">
                        @csrf
                        <div class="input-group mb-3">
                            <input type="email" class="form-control" placeholder="Email" name="email">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        @error('email')
                        {{$message}}
                        @enderror
                        <div class="input-group mb-3">
                            <input type="password" class="form-control" placeholder="Password" name="password">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        @error('password')
                        {{$message}}
                        @enderror
                        <div class="row">
                            <div class="col-8">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="remember" name="remember">
                                    <label for="remember">
                                        {{__('login.remember_me')}}
                                    </label>
                                </div>
                                <a href="{{route('customer.doregister')}}">Register</a>
                            </div>



                            <!-- /.col -->
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">{{__('login.sign_in')}}</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>



                </div>
                <!-- /.login-card-body -->
            </div>

        </div>
    </section>
    <!--================End Checkout Area =================-->

    @endsection

resources/views/customer/login1.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Login') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('login') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">

                                @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-md-6 offset-md-4">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>

                                    <label class="form-check-label" for="remember">
                                        {{ __('Remember Me') }}
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Login') }}
                                </button>

                                @if (Route::has('password.request'))
                                    <a class="btn btn-link" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>
                                @endif
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/register.blade.php
@extends('layouts.frontend')

@section('main-content')
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Customer</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="single-product.html">Customer Login</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
        <div class="container">

            <div class="card">
                <h1>    Register Form</h1>
                <div class="card-body login-card-body">
                    <p class="login-box-msg">Please register</p>

                    <form method="POST" action="{{ route('customer.doregister') }}">
                        @csrf
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Name" name="name" required>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        @error('name')
                        {{$message}}
                        @enderror
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Address" name="address" required>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        @error('address')
                        {{$message}}
                        @enderror
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Country" name="country" required>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>

                        @error('country')
                        {{$message}}
                        @enderror
                        <div class="input-group mb-3">
                            <input type="email" class="form-control" placeholder="Email" name="email" required>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        @error('email')
                        {{$message}}
                        @enderror

                        <div class="input-group mb-3">
                            <input type="password" class="form-control" placeholder="Password" name="password" required>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        @error('password')
                        {{$message}}
                        @enderror
                        <div class="input-group mb-3">
                            <input type="number" class="form-control" placeholder="Contact" name="contact" required>
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        @error('contact')
                        {{$message}}
                        @enderror

                        <div class="row">
                            <div class="col-8">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="remember" name="remember">
                                    <label for="remember">
                                        {{__('login.remember_me')}}
                                    </label>
                                </div>
                            </div>
                            <!-- /.col -->
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">{{__('login.sign_in')}}</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>



                </div>
                <!-- /.login-card-body -->
            </div>

        </div>
    </section>
    <!--================End Checkout Area =================-->

@endsection

resources/views/customer/verify.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Verify Your Email Address') }}</div>

                <div class="card-body">
                    @if (session('resent'))
                        <div class="alert alert-success" role="alert">
                            {{ __('A fresh verification link has been sent to your email address.') }}
                        </div>
                    @endif

                    {{ __('Before proceeding, please check your email for a verification link.') }}
                    {{ __('If you did not receive the email') }},
                    <form class="d-inline" method="POST" action="{{ route('verification.resend') }}">
                        @csrf
                        <button type="submit" class="btn btn-link p-0 m-0 align-baseline">{{ __('click here to request another') }}</button>.
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection