routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Frontend\PaypalController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('create-transaction/{checkout_id?}', [PayPalController::class, 'createTransaction'])->name('createTransaction');
Route::get('process-transaction', [PayPalController::class, 'processTransaction'])->name('processTransaction');
Route::get('success-transaction', [PayPalController::class, 'successTransaction'])->name('successTransaction');
Route::get('cancel-transaction', [PayPalController::class, 'cancelTransaction'])->name('cancelTransaction');


Route::prefix('/customer')->name('customer.')->namespace('Customer')->group(function(){

    /**
     * Admin Auth Route(s)
     */
    Route::namespace('Auth')->group(function(){

        //Login Routes
        Route::get('/login', [\App\Http\Controllers\Customer\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login',[\App\Http\Controllers\Customer\Auth\LoginController::class, 'login'])->name('dologin');
        Route::post('/logout',[\App\Http\Controllers\Customer\Auth\LoginController::class, 'logout'])->name('logout');

        //Register Routes
         Route::get('/register',[\App\Http\Controllers\Customer\Auth\RegisterController::class, 'showRegistrationForm'])->name('register');
         Route::post('/register',[\App\Http\Controllers\Customer\Auth\RegisterController::class, 'doregister'])->name('doregister');

    });

    Route::get('/dashboard',[\App\Http\Controllers\Customer\HomeController::class,'index'])->name('home');

    //Put all of your admin routes here...

});


Route::name('frontend.')->group(function() {
    Route::post('/product/rating', [\App\Http\Controllers\Frontend\FrontendController::class, 'rating'])->name('product.rating');
    Route::post('/category/filter_product', [\App\Http\Controllers\Frontend\FrontendController::class, 'filterProduct'])->name('category.filter_product');
    Route::get('/', [\App\Http\Controllers\Frontend\FrontendController::class, 'index'])->name('index');
    Route::get('/category/{slug}', [\App\Http\Controllers\Frontend\FrontendController::class, 'category'])->name('category');
    Route::get('/subcategory/{slug}', [\App\Http\Controllers\Frontend\FrontendController::class, 'subcategory'])->name('subcategory');
    Route::get('/product/{slug}', [\App\Http\Controllers\Frontend\FrontendController::class, 'product'])->name('product');
    Route::post('/cart/make_order', [\App\Http\Controllers\Frontend\CartController::class, 'makeOrder'])->name('cart.make_order');
});
Route::post('/cart/add', [\App\Http\Controllers\Frontend\CartController::class, 'add'])->name('frontend.cart.add');
Route::get('/cart', [\App\Http\Controllers\Frontend\CartController::class, 'index'])->name('cart.index');
Route::post('/cart/update', [\App\Http\Controllers\Frontend\CartController::class, 'update'])->name('cart.update');
Route::get('/cart/checkout', [\App\Http\Controllers\Frontend\CartController::class, 'checkout'])->name('cart.checkout');
Route::post('/cart/apply_coupon', [\App\Http\Controllers\Frontend\CartController::class, 'applyCoupon'])->name('cart.apply_coupon');

Auth::routes(['register' => true]);
Route::middleware(['auth','permission'])->group(function() {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});
Route::post('/category/getsubcategory', [\App\Http\Controllers\Backend\CategoryController::class, 'getSubcategory'])->name('category.getsubcategory');

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::prefix('backend')->name('backend.')->middleware(['auth'])->group(function(){
    Route::get('/role/assign_form/{id}', [\App\Http\Controllers\Backend\RoleController::class, 'assignForm'])->name('role.assign_form');
    Route::post('/role/assign_permission', [\App\Http\Controllers\Backend\RoleController::class, 'assignPermission'])->name('role.assign_permission');
    Route::resource('/category', \App\Http\Controllers\Backend\CategoryController::class );
    Route::resource('/subcategory',\App\Http\Controllers\Backend\SubCategoryController::class);
    Route::resource('/product',\App\Http\Controllers\Backend\ProductController::class);
    Route::resource('/unit',\App\Http\Controllers\Backend\UnitController::class);
    Route::resource('/tag', \App\Http\Controllers\Backend\TagController::class );
    Route::resource('/attribute',\App\Http\Controllers\Backend\AttributeController::class);
    Route::resource('/module',\App\Http\Controllers\Backend\ModuleController::class);
    Route::resource('/permission',\App\Http\Controllers\Backend\PermissionController::class);
    Route::resource('/role',\App\Http\Controllers\Backend\RoleController::class);
    Route::resource('/user',\App\Http\Controllers\Backend\UserController::class);
    Route::resource('/setting',\App\Http\Controllers\Backend\SettingController::class);
    Route::resource('/coupon',\App\Http\Controllers\Backend\CouponController::class);
    Route::resource('/rating',\App\Http\Controllers\Backend\RatingController::class);
});

app/Http/Controllers/Frontend/CartController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Checkout;
use App\Models\CheckoutDetails;
use App\Models\Coupon;
use App\Models\Product;
use App\Models\Subcategory;
use Gloudemans\Shoppingcart\Facades\Cart;
use Illuminate\Http\Request;

class CartController extends FrontBaseController
{
    function add(Request  $request){
       $product = Product::find($request->product_id);
        Cart::add(['id' =>$request->product_id , 'name' => $product->title, 'qty' => $request->qty, 'price' => $product->price-$product->discount, 'weight' =>1 , 'options' => $request->attribute]);
        $request->session()->flash('success','Item added into cart successfully');
        return redirect()->route('frontend.product',$product->slug);
    }

    function  index(){
        $data['carts'] = Cart::content();
        //dd($data['carts']);
        return view($this->__loadDataToView('frontend.cart.index'),compact('data'));
    }

    function  update(Request  $request){
        Cart::update($request->rowId, $request->qty);
        $request->session()->flash('success','Cart updated successfully');
        return redirect()->route('cart.index');
    }


    function  applyCoupon(Request  $request){
        $date = date('Y-m-d');
        $coupon = Coupon::where('status',1)->where('code',$request->code)->where('date_from', '<=' ,$date  )->where('date_to', '>=' ,$date  )->first();
        $discount = 0;
        $items = Cart::content();
        $subtotal = 0;
        foreach ($items as $item)
        {
            $subtotal += $item->qty  * $item->price;
        }
        if ($coupon){
            $request->session()->put('coupon_code' , $coupon->code );
            $request->session()->put('discount_percentage' , $coupon->discount_percentage );
            $discount = ($subtotal * $coupon->discount_percentage)/100;
            $final = $subtotal - $discount;
        } else {
            $final= $subtotal;
        }
        return ['final' => $final,'discount' => $discount,'subtotal' => $subtotal];
    }

    function  checkout(){
        $data['carts'] = Cart::content();
        return view($this->__loadDataToView('frontend.cart.checkout'),compact('data'));
    }

    function  makeOrder(Request  $request){
        $payment_type = $request->payment_type;
        $request->request->add(['checkout_code' => uniqid()]);
        $data = Checkout::create($request->all());
        if ($data){
            $details['checkout_id'] = $data->id;
            foreach (Cart::content() as $rowId => $item){
                $details['product_id'] = $item->id;
                $details['price'] = $item->price;
                $details['quantity'] = $item->qty;
                CheckoutDetails::create($details);
                Cart::remove($rowId);
            }
            $request->session()->flash('success','Checkout successfully: Your checkout code is : ' . $data->checkout_code);
        } else {
            $request->session()->flash('error' , 'Checkout Failed');
        }

        if ( $payment_type == 'paypal'){
            return redirect()->to('create-transaction/' . $data->id);
        } else {
            return redirect()->route('cart.index');
        }
    }
}

app/Http/Controllers/Frontend/FrontBaseController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;

class FrontBaseController extends Controller
{
    protected function __loadDataToView($viewPath){
    view()->composer($viewPath,function($view){
        $category = Category::where('status',1)->get();
        $view->with('category',$category);

    });
    return $viewPath;
}
}

app/Http/Controllers/Frontend/FrontendController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Customer;
use App\Models\Product;
use App\Models\Rating;
use App\Models\Subcategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FrontendController extends FrontBaseController
{
    public  function  index(){
        $data['latest_products'] = Product::where('status',1)->orderby('created_at','desc')->limit(8)->get();
        return view($this->__loadDataToView('frontend.index'),compact('data'));
    }

    public  function  category($slug){
        $data['details'] = Category::where('slug',$slug)->first();
        $data['products'] = $data['details']->products()->orderBy('price')->get();
        $data['deals_of_the_weeks'] = Product::where('feature_product',1)->get();
        return view($this->__loadDataToView('frontend.category'),compact('data'));
    }

    public  function  product($slug){
        $data = [];
        $data['details'] = Product::where('slug',$slug)->first();

        if (!empty(Auth::guard('customer')->user()->id)){
            $data['customers'] = Customer::all();
            $dataSet = [];
            foreach($data['customers'] as $customer){
                $dataSet[$customer->id] = Rating::where('customer_id',$customer->id)->pluck('rate','product_id')->toArray();
            }
            $data['recommended_products'] = $this->getRecommendations($dataSet, Auth::guard('customer')->user()->id);
            $data['ratedata'] =  Rating::where('customer_id' ,Auth::guard('customer')->user()->id)->where('product_id',$data['details']->id)->count();
            $data['ratings'] =  Rating::where('product_id',$data['details']->id)->get();

        }

        return view($this->__loadDataToView('frontend.product'),compact('data'));
    }

    public function  subcategory($slug){
        $data['details'] = Subcategory::where('slug',$slug)->first();
        $data['products'] = $data['details']->products()->get();
        return view($this->__loadDataToView('frontend.subcategory'),compact('data'));
    }
    public function  filterProduct(Request $request){

      $products = Product::where('category_id',$request->catid)
                              ->where(function($q) use ($request){
                                  $q->where('price','>=', $request->lower_price)
                                      ->where('price','<=', $request->upper_price);
                              })->orderby('price',$request->order)
                        ->get();
      $html = "";
      foreach ($products as $product){
          $image = $product->productImage()->first();
          $html .= "<div class='col-lg-4 col-md-6'>
							<div class='single-product'>
								<img class='img-fluid' src='" .asset('images/backend/product/255_271_' . $image->image_name) . "' alt=''>
								<div class='product-details'>
									<h6>$product->title</h6>
									<div class='price'>
										<h6>$product->price</h6>
										<h6 class='l-through'>$product->price</h6>
									</div>
									<div class='prd-bottom'>

										<a href='' class='social-info'>
											<span class='ti-bag'></span>
											<p class='hover-text'>add to bag</p>
										</a>
										<a href='' class='social-info'>
											<span class='lnr lnr-heart'></span>
											<p class='hover-text'>Wishlist</p>
										</a>
										<a href='' class='social-info'>
											<span class='lnr lnr-sync'></span>
											<p class='hover-text'>compare</p>
										</a>
										<a href='" . route('frontend.product',$product->slug)  ."' class='social-info'>
											<span class='lnr lnr-move'></span>
											<p class='hover-text'>view more</p>
										</a>
									</div>
								</div>
							</div>
						</div>";

      }
        return $html;
    }

    function rating(Request  $request){
        $request->request->add(['customer_id' => Auth::guard('customer')->user()->id]);
        Rating::create($request->all());
        $product = Product::find($request->product_id);
        return redirect()->route('frontend.product',$product->slug);

    }

    //Euclidean distance
    public function similarityDistance($preferences, $person1, $person2)
    {
        $similar = array();
        $sum = 0;

        foreach($preferences[$person1] as $key=>$value)
        {
            if(array_key_exists($key, $preferences[$person2]))
                $similar[$key] = 1;
        }

        if(count($similar) == 0)
            return 0;

        foreach($preferences[$person1] as $key=>$value)
        {
            if(array_key_exists($key, $preferences[$person2]))
                $sum = $sum + pow($value - $preferences[$person2][$key], 2);
        }

        return  1/(1 + sqrt($sum));
    }


    public function matchItems($preferences, $person)
    {
        $score = array();

        foreach($preferences as $otherPerson=>$values)
        {
            if($otherPerson !== $person)
            {
                $sim = $this->similarityDistance($preferences, $person, $otherPerson);

                if($sim > 0)
                    $score[$otherPerson] = $sim;
            }
        }

        array_multisort($score, SORT_DESC);
        return $score;

    }


    public function transformPreferences($preferences)
    {
        $result = array();

        foreach($preferences as $otherPerson => $values)
        {
            foreach($values as $key => $value)
            {
                $result[$key][$otherPerson] = $value;
            }
        }

        return $result;
    }


    public function getRecommendations($preferences, $person)
    {

        $total = array();
        $simSums = array();
        $ranks = array();
        $sim = 0;

        foreach($preferences as $otherPerson=>$values)
        {

            if($otherPerson != $person)
            {
                $sim = $this->similarityDistance($preferences, $person, $otherPerson);
            }

            if($sim > 0)
            {
                foreach($preferences[$otherPerson] as $key=>$value)
                {
                    if(!array_key_exists($key, $preferences[$person]))
                    {

                        if(!array_key_exists($key, $total)) {
                            $total[$key] = 0;
                        }
                        $total[$key] += $preferences[$otherPerson][$key] * $sim;

                        if(!array_key_exists($key, $simSums)) {
                            $simSums[$key] = 0;
                        }
                        $simSums[$key] += $sim;
                    }
                }

            }
        }


        foreach($total as $key=>$value)
        {
            $ranks[$key] = $value / $simSums[$key];
        }
//        array_multisort($ranks, SORT_DESC);
        return $ranks;

    }

}

resources/views/frontend/cart/checkout.blade.php
@extends('layouts.frontend')

@section('main-content')
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Checkout</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="single-product.html">Checkout</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Checkout Area =================-->
    <section class="checkout_area section_gap">
        <div class="container">
            <div class="returning_customer">
                <div class="check_title">
                    <h2>Returning Customer? <a href="#">Click here to login</a></h2>
                </div>
                <p>If you have shopped with us before, please enter your details in the boxes below. If you are a new
                    customer, please proceed to the Billing & Shipping section.</p>
                <form class="row contact_form" action="#" method="post" novalidate="novalidate">
                    <div class="col-md-6 form-group p_star">
                        <input type="text" class="form-control" id="name" name="name">
                        <span class="placeholder" data-placeholder="Username or Email"></span>
                    </div>
                    <div class="col-md-6 form-group p_star">
                        <input type="password" class="form-control" id="password" name="password">
                        <span class="placeholder" data-placeholder="Password"></span>
                    </div>
                    <div class="col-md-12 form-group">
                        <button type="submit" value="submit" class="primary-btn">login</button>
                        <div class="creat_account">
                            <input type="checkbox" id="f-option" name="selector">
                            <label for="f-option">Remember me</label>
                        </div>
                        <a class="lost_pass" href="#">Lost your password?</a>
                    </div>
                </form>
            </div>
            <div class="cupon_area">
                <div class="check_title">
                    <h2>Have a coupon? <a href="#">Click here to enter your code</a></h2>
                </div>
                <input type="text" placeholder="Enter coupon code">
                <a class="tp_btn" href="#">Apply Coupon</a>
            </div>
            <form class="row contact_form" action="{{route('frontend.cart.make_order')}}" method="post" novalidate="novalidate">
                @csrf

            <div class="billing_details">
                <div class="row">
                    <div class="col-lg-8">
                        <h3>Billing Details</h3>
                            <div class="col-md-6 form-group p_star">
                                <input type="text" class="form-control" id="first" name="name" placeholder="Enter name">
{{--                                <span class="placeholder" data-placeholder="First name"></span>--}}
                            </div>

                            <div class="col-md-12 form-group">
                                <input type="text" class="form-control" id="company" name="company" placeholder="Company name">
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <input type="text" class="form-control" id="number" name="contact" placeholder="contact">
{{--                                <span class="placeholder" data-placeholder="Phone number"></span>--}}
                            </div>
                            <div class="col-md-6 form-group p_star">
                                <input type="text" class="form-control" id="email" name="email" placeholder="email">
{{--                                <span class="placeholder" data-placeholder="Email Address"></span>--}}
                            </div>
                            <div class="col-md-12 form-group p_star">
                                <input type="text" class="form-control" id="add1" name="address" placeholder="enter address">
{{--                                <span class="placeholder" data-placeholder="Address line 01"></span>--}}
                            </div>


                            <div class="col-md-12 form-group p_star">
                                <select class="country_select" name="country">
                                    <option value="nepal">Nepal</option>
                                    <option value="india">India</option>
                                    <option value="china">China</option>
                                </select>
                            </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="order_box">
                            <h2>Your Order</h2>
                            <ul class="list">
                                <li><a href="#">Product <span>Total</span></a></li>
                                @php
                                  $total = 0;
                                @endphp
                                @foreach($data['carts'] as $cart)
                                    @php
                                        $total += $cart->qty*$cart->price;
                                      $product = \App\Models\Product::find($cart->id);

                                    @endphp
                                    <li><a href="#">{{$product->title}} <span class="middle"> X  {{$cart->qty}}</span> <span class="last">{{ $cart->qty*$cart->price}}</span></a></li>
                                @endforeach
                            </ul>
                            @php
                                if (session('discount_percentage')){
                                    $discount = ($total * session('discount_percentage'))/100;
                                    $final = $total-$discount;
                                } else {
                                    $discount = 0;
                                    $final = $total;
                                }

                            @endphp
                            <ul class="list list_2">
                                <input type="hidden" name="subtotal" value="{{$total}}">
                                <input type="hidden" name="discount" value="{{$discount  }}">
                                <input type="hidden" name="total" value="{{$final}}">

                                <li><a href="#">Subtotal <span>{{$total}}</span></a></li>
                                <li><a href="#">Discount <span> {{$discount}}</span></a></li>
                                <li><a href="#">Total <span>{{$final}}</span></a></li>
                            </ul>
                            <div class="payment_item">
                                <div class="radion_btn">
                                    <input type="radio" id="f-option5" name="payment_type" value="cod">
                                    <label for="f-option5">COD</label>
                                    <div class="check"></div>
                                </div>
                                <p>Please send a check to Store Name, Store Street, Store Town, Store State / County,
                                    Store Postcode.</p>
                            </div>
                            <div class="payment_item active">
                                <div class="radion_btn">
                                    <input type="radio" id="f-option6" name="payment_type" value="paypal">
                                    <label for="f-option6">Paypal </label>
                                    <img src="img/product/card.jpg" alt="">
                                    <div class="check"></div>
                                </div>
                                <p>Pay via PayPal; you can pay with your credit card if you don’t have a PayPal
                                    account.</p>
                            </div>
                            <div class="creat_account">
                                <input type="checkbox" id="f-option4" name="selector">
                                <label for="f-option4">I’ve read and accept the </label>
                                <a href="#">terms & conditions*</a>
                            </div>
                            <button class="primary-btn" href="#">Make Order</button>
                        </div>
                    </div>
                </div>

            </div>
        </form>

        </div>
    </section>
    <!--================End Checkout Area =================-->
@endsection
@section('js')
@endsection

resources/views/frontend/cart/make_transaction.blade.php
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Pay $1000</title>
    <script src="https://www.paypal.com/sdk/js?client-id={{ env('PAYPAL_SANDBOX_CLIENT_ID') }}"></script>
</head>
<body>
@if(!empty($data))
    <a class="btn btn-primary m-3" href="{{ route('processTransaction') }}">Pay {{ $data['checkout']->total }}</a>
@endif
@if(\Session::has('error'))
    <div class="alert alert-danger">{{ \Session::get('error') }}</div>
    {{ \Session::forget('error') }}
@endif
@if(\Session::has('success'))
    <div class="alert alert-success">{{ \Session::get('success') }}</div>
    {{ \Session::forget('success') }}
@endif
</body>
</html>